!INTERFILE  :=
!imaging modality := PT
name of data file := STIR_scanner.hs
originating system := GE Discovery 690
!version of keys := STIR4.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 1
matrix axis label [3] := view
!matrix size [3] := 288
matrix axis label [2] := axial coordinate
!matrix size [2] := { 24}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 381
minimum ring difference per segment := { 0}
maximum ring difference per segment := { 0}
Scanner parameters:= 
Scanner type := GE Discovery 690
Number of rings                          := 24
Number of detectors per ring             := 576
Inner ring diameter (cm)                 := 81.02
Average depth of interaction (cm)        := 0.94
Distance between rings (cm)              := 0.654
Default bin size (cm)                    := 0.21306
View offset (degrees)                    := -5.021
Maximum number of non-arc-corrected bins := 381
Default number of arc-corrected bins     := 331
Number of TOF time bins :=55
Size of timing bin (ps) :=89
Timing resolution (ps) :=550
Energy resolution := 0.124
Reference energy (in keV) := 511
Number of blocks per bucket in transaxial direction         := 2
Number of blocks per bucket in axial direction              := 4
Number of crystals per block in axial direction             := 6
Number of crystals per block in transaxial direction        := 9
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 1
Number of crystals per singles unit in transaxial direction := 1
end scanner parameters:=
effective central bin size (cm) := 0.226074
number of time frames := 1
number of energy windows := 1
energy window lower level[1] := 425
energy window upper level[1] :=  650
start vertical bed position (mm) := 0
start horizontal bed position (mm) := 0
!END OF INTERFILE :=
