## AUTHOR: Elise Emond
## AUTHOR: Ludovica Brusaferri
## Copyright (C) 2018-2019 University College London
## Licensed under the Apache License, Version 2.0

/gate/source/addSource Source1

/gate/source/Source1/setActivity 1000 becquerel
/gate/source/Source1/setType backtoback
/gate/source/Source1/gps/particle gamma
/gate/source/Source1/setForcedUnstableFlag false
/gate/source/Source1/setForcedHalfLife 6586 s
/gate/source/Source1/gps/energytype Mono
/gate/source/Source1/gps/monoenergy 511. keV
/gate/source/Source1/gps/type Point
/gate/source/Source1/gps/angtype iso
/gate/source/list
