## AUTHOR: Elise Emond
## AUTHOR: Ludovica Brusaferri
## AUTHOR: Vesna Cuplov
## Copyright (C) 2014-2019 University College London
## Licensed under the Apache License, Version 2.0
## digitiser for mMR Scanner


## R E A D O U T

## For details regarding readout, see: https://opengate.readthedocs.io/en/latest/digitizer_and_detector_modeling.html#readout
/gate/digitizer/Singles/insert                        adder
/gate/digitizer/Singles/insert                        readout
/gate/digitizer/Singles/readout/setDepth              1


## C R Y S T A L   B L U R R I N G 

/gate/digitizer/Singles/insert crystalblurring
/gate/digitizer/Singles/crystalblurring/setCrystalResolutionMin 0.130
/gate/digitizer/Singles/crystalblurring/setCrystalResolutionMax 0.145
/gate/digitizer/Singles/crystalblurring/setCrystalQE 0.9
/gate/digitizer/Singles/crystalblurring/setCrystalEnergyOfReference 511. keV


## E N E R G Y   T H R E S H O L D

/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 430. keV  # Not Verified
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 610. keV


## T I M I N G   R E S O L U T I O N

/gate/digitizer/Singles/insert timeResolution
/gate/digitizer/Singles/timeResolution/setTimeResolution 2.92969 ns


## D E A D T I M E

/gate/digitizer/Singles/insert deadtime
/gate/digitizer/Singles/deadtime/setDeadTime 432. ns
/gate/digitizer/Singles/deadtime/setMode paralysable
/gate/digitizer/Singles/deadtime/chooseDTVolume block


## C O I N C I D E N C E S

/gate/digitizer/Coincidences/setWindow 5.85938 ns
/gate/digitizer/Coincidences/setOffset 0. ns
/gate/digitizer/Coincidences/MultiplesPolicy takeWinnerOfGoods
/gate/digitizer/Coincidences/minSectorDifference 8
/gate/digitizer/Coincidences/describe

## D E L A Y

/gate/digitizer/name   Delayed
/gate/digitizer/insert   coincidenceSorter
/gate/digitizer/Delayed/setInputName   Singles
/gate/digitizer/Delayed/setOffset   200. ns
/gate/digitizer/Delayed/setWindow   5.85938 ns
/gate/digitizer/Delayed/minSectorDifference   8  ## GATE default=2. For this scanner, STIR does not unlist any block difference < 8. This value has been optimised to reduce the root file size

