#! /bin/sh
## AUTHOR: Robert Twyman
## Copyright (C) 2020 University College London
## Licensed under the Apache License, Version 2.0

## - Script used to generate activity and attenuation images in STIR 
##   from parameter files, if a .par file is given
## - A modification is made to the scale of the attenuation file for GATE.
## - Converts header file (.hv) to GATE compatable header (.h33) using
##   STIR2GATE_interfile.sh.

# NOTE: DO NOT EDIT THIS FILE TO INCLUDE ECHO, THE OUTPUT IS REQUIRED IN MANY PLACES

if [ $# -ne 2 ]; then
  echo "Usage:"$0 "Activity(.par/.hv) AttenuationPar(.par/.hv)" 1>&2
  echo "Returns Activity and Attenuation filenames."
  exit 1
fi

ACTIVITY=$1  ## Activity parameter file
ATTENUATION=$2  ## Attenuation parameter file
STIRGATEHome=$PWD  

ACT_EXT="${ACTIVITY##*.}"
ATT_EXT="${ATTENUATION##*.}"

if [ "$ACT_EXT" == "par" -a "$ATT_EXT" == "par" ]; then
	# If .par files are given, generate the data
	ActivityFilename=`awk -F:= '/output filename/ { print $2 }' $ACTIVITY`
	AttenuationFilename=`awk -F:= '/output filename/ { print $2 }' $ATTENUATION`
	## Generate images
	generate_image $Activity 
	generate_image $ATTENUATION

elif [ "$ACT_EXT" == "hv" -a "$ATT_EXT" == "hv" ]; then
	## If .hv files are given, set filename prefixes
	ActivityFilename="${ACTIVITY%.*}"
	AttenuationFilename="${ATTENUATION%.*}"
fi

## Modify the scale of the attenuation file for GATE (requires int values).
AttenuationFilenameGATE=$AttenuationFilename"_GATE"
SubScripts/ModifyAttenuationImageForGate.sh $AttenuationFilename".hv" $AttenuationFilenameGATE

## Process .hv file into .h33 files.
## This adds fields: "!number of slices :=" and "slice thickness (pixels) :=".
sh ./SubScripts/STIR2GATE_interfile.sh $ActivityFilename".h33" $ActivityFilename".hv" 
sh ./SubScripts/STIR2GATE_interfile.sh $AttenuationFilenameGATE".h33" $AttenuationFilenameGATE".hv" 

echo $ActivityFilename".h33" $AttenuationFilenameGATE".h33"

exit 0
