## AUTHOR: Robert Twyman
## Copyright (C) 2020 University College London
## Licensed under the Apache License, Version 2.0 (the "License")
## File contains GATE commands for output
## Will output two root files (Singles and Coincidences), each containing a single branch


## Output ROOT files

## Save Singles and Coincidence Trees in their own files. Disable many aspects of Singles 

/gate/output/tree/enable
/gate/output/tree/addFileName {StoreRootFilesDirectory}/{ROOT_FILENAME}.root

## S I N G L E S 
/gate/output/tree/addCollection Singles 

## (exclude all the non-required branches)
/gate/output/tree/Singles/branches/sourceID/disable
/gate/output/tree/Singles/branches/runID/disable
/gate/output/tree/Singles/branches/eventID/disable
/gate/output/tree/Singles/branches/sourcePosX/disable
/gate/output/tree/Singles/branches/sourcePosY/disable
/gate/output/tree/Singles/branches/sourcePosZ/disable
/gate/output/tree/Singles/branches/globalPosX/disable
/gate/output/tree/Singles/branches/globalPosY/disable
/gate/output/tree/Singles/branches/globalPosZ/disable
/gate/output/tree/Singles/branches/time/disable
/gate/output/tree/Singles/branches/energy/disable
/gate/output/tree/Singles/branches/comptonPhantom/disable
/gate/output/tree/Singles/branches/comptonCrystal/disable
/gate/output/tree/Singles/branches/RayleighPhantom/disable
/gate/output/tree/Singles/branches/RayleighCrystal/disable
/gate/output/tree/Singles/branches/comptVolName/disable
/gate/output/tree/Singles/branches/rotationAngle/disable
/gate/output/tree/Singles/branches/axialPos/disable


## C O I N C I D E N C E S
/gate/output/tree/addCollection Coincidences

## (exclude all the non-required branches)
/gate/output/tree/Coincidences/branches/runID/disable
/gate/output/tree/Coincidences/branches/rotationAngle/disable
/gate/output/tree/Coincidences/branches/axialPos/disable


## S U M M A R Y   O U T P U T
/gate/output/summary/enable
/gate/output/summary/setFileName Output/digit_summary.txt
/gate/output/summary/addCollection Singles
/gate/output/summary/addCollection Coincidences

