## AUTHOR: Elise Emond
## AUTHOR: Ludovica Brusaferri
## Copyright (C) 2018-2019 University College London
## Licensed under the Apache License, Version 2.0

/vis/open                           OGLI
/vis/viewer/set/viewpointThetaPhi   60 60
/vis/viewer/zoom                    1.0
/vis/drawVolume
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction         accumulate 100000
/vis/scene/add/axes
